platform :ios, '10.0'

target 'gingabox' do
  
require_relative '../node_modules/react-native-unimodules/cocoapods'

# Add new pods below this line



pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

pod 'react-native-maps', :path => '../node_modules/react-native-maps'


pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

pod 'react-native-webview', :path => '../node_modules/react-native-webview'

pod 'RNScreens', :path => '../node_modules/react-native-screens'

pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'

pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


pod 'RNShare', :path => '../node_modules/react-native-share'
pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

pod 'TouchID', :path => '../node_modules/react-native-touch-id'

rn_path = '../node_modules/react-native'
rn_maps_path = '../node_modules/react-native-maps'

use_unimodules!

# See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
pod 'React', path: rn_path, subspecs: [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
]

# React Native third party dependencies podspecs
pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"

pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

end

post_install do |installer|
installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '3.0'    # 4.0
  end
  targets_to_ignore = %w(React yoga)
    
  if targets_to_ignore.include? target.name
    target.remove_from_project
  end
end
end